"""Pure downstream invocation and completion projections for the T09 Retry 3 finalizer.

This module owns no empirical, provider, budget, raw-seal, selection, or checkpoint
state.  A frozen supervisor supplies already-validated identities, validates every
returned mount/argument and every output hash, and alone executes or selects results.
"""

from __future__ import annotations

from typing import Any


def build_finalizer_argv(
    *,
    docker_prefix: list[str],
    artifact_root: str,
    raw_root: str,
    finalized_root: str,
    control_root: str,
    giclab_source_root: str,
    finalizer_source: str,
    evaluator_overlay: str,
    execution_contract: str,
    command_manifests: str,
    condition_plans: str,
    schemas_root: str,
    image_id: str,
    condition_plan_name: str,
    output_root: str,
    raw_output_root: str,
    finalized_output_relative: str,
    run_id: str,
    package_commit: str,
    finalizer_commit: str,
    finalizer_source_sha256: str,
    finalizer_projection_source_sha256: str,
    finalizer_dependency_manifest_sha256: str,
    frozen_run_manifest_sha256: str,
    evaluator_revalidation_relative: str,
    execution_contract_sha256: str,
    command_manifests_sha256: str,
) -> list[str]:
    """Return the declarative network-none Docker invocation for one derived root."""

    return [
        *docker_prefix,
        "run",
        "--rm",
        "--network",
        "none",
        "--read-only",
        "--user",
        "1000:1000",
        "--env",
        "PYTHONPATH=/opt/evaluator/.venv/lib/python3.11/site-packages:/opt/giclab-src",
        "--mount",
        f"type=bind,src={artifact_root},dst=/opt/giclab-artifacts,readonly",
        "--mount",
        f"type=bind,src={raw_root},dst=/opt/giclab-raw,readonly",
        "--mount",
        f"type=bind,src={finalized_root},dst=/opt/giclab-finalized",
        "--mount",
        f"type=bind,src={control_root},dst=/opt/giclab-control,readonly",
        "--mount",
        f"type=bind,src={giclab_source_root},dst=/opt/giclab-src/giclab,readonly",
        "--mount",
        f"type=bind,src={finalizer_source},dst=/opt/giclab/t09_evaluate_attempt.py,readonly",
        "--mount",
        f"type=bind,src={evaluator_overlay},dst=/opt/evaluator,readonly",
        "--mount",
        f"type=bind,src={execution_contract},dst=/opt/giclab-contracts/execution.json,readonly",
        "--mount",
        f"type=bind,src={command_manifests},dst=/opt/giclab-contracts/T09_PILOT_COMMAND_MANIFESTS.json,readonly",
        "--mount",
        f"type=bind,src={condition_plans},dst=/opt/giclab-contracts/conditions,readonly",
        "--mount",
        f"type=bind,src={schemas_root},dst=/opt/giclab-schemas,readonly",
        "--entrypoint",
        "/opt/sira/.venv/bin/python",
        image_id,
        "/opt/giclab/t09_evaluate_attempt.py",
        "--execution-contract",
        "/opt/giclab-contracts/execution.json",
        "--execution-contract-sha256",
        execution_contract_sha256,
        "--command-manifests",
        "/opt/giclab-contracts/T09_PILOT_COMMAND_MANIFESTS.json",
        "--command-manifests-sha256",
        command_manifests_sha256,
        "--condition-plan",
        f"/opt/giclab-contracts/conditions/{condition_plan_name}",
        "--raw-attempt-root",
        "/opt/giclab-raw",
        "--raw-output-relative",
        raw_output_root,
        "--finalized-attempt-root",
        "/opt/giclab-finalized",
        "--finalized-output-relative",
        finalized_output_relative,
        "--artifact-root",
        "/opt/giclab-artifacts",
        "--raw-attempt-manifest",
        f"/opt/giclab-artifacts/{output_root}/raw-attempt-manifest.json",
        "--raw-attempt-receipt",
        f"/opt/giclab-artifacts/{output_root}/raw-attempt-complete.json",
        "--run-id",
        run_id,
        "--package-commit",
        package_commit,
        "--finalizer-commit",
        finalizer_commit,
        "--finalizer-execution-mode",
        "qualified-image",
        "--finalizer-source-sha256",
        finalizer_source_sha256,
        "--finalizer-projection-source-sha256",
        finalizer_projection_source_sha256,
        "--finalizer-dependency-manifest-sha256",
        finalizer_dependency_manifest_sha256,
        "--finalizer-runtime-qualification",
        "/opt/giclab-control/frozen-run-manifest.json",
        "--finalizer-runtime-qualification-sha256",
        frozen_run_manifest_sha256,
        "--frozen-run-manifest",
        "/opt/giclab-control/frozen-run-manifest.json",
        "--frozen-run-manifest-sha256",
        frozen_run_manifest_sha256,
        "--replacement-image-id",
        image_id,
        "--host-cleanup-receipt",
        "/opt/giclab-raw/host-cleanup-receipt.json",
        "--evaluator-root",
        "/opt/sira/evaluation/fanout",
        "--evaluator-overlay-revalidation",
        f"/opt/giclab-artifacts/{evaluator_revalidation_relative}",
        "--dataset",
        "/opt/sira/data/fanout-final-dev.json",
        "--score-schema",
        "/opt/giclab-schemas/t09-sira-pilot-score.schema.json",
        "--evidence-schema",
        "/opt/giclab-schemas/t09-sira-pilot-evidence.schema.json",
    ]


def build_completion_projection(
    *,
    plan_id: str,
    host_run_id: str,
    run_id: str,
    raw_manifest_sha256_before: str,
    raw_manifest_sha256_after: str,
    raw_receipt_sha256: str,
    raw_manifest_payload_sha256: str,
    raw_receipt_payload_sha256: str,
    output_files: list[dict[str, object]],
    output_files_sha256: str,
    outcome_sha256: str,
    evidence_index_sha256: str,
    semantic_projection_file_sha256: str,
    semantic_projection_sha256: str,
    finalizer_closure: dict[str, str],
    finalizer_dependency_manifest_sha256: str,
    network: str,
) -> dict[str, Any]:
    """Return the completion receipt payload that the frozen supervisor revalidates."""

    return {
        "schema_version": "0.1.0",
        "plan_id": plan_id,
        "host_run_id": host_run_id,
        "run_id": run_id,
        "raw_manifest_sha256_before": raw_manifest_sha256_before,
        "raw_manifest_sha256_after": raw_manifest_sha256_after,
        "raw_receipt_sha256": raw_receipt_sha256,
        "raw_manifest_payload_sha256": raw_manifest_payload_sha256,
        "raw_receipt_payload_sha256": raw_receipt_payload_sha256,
        "output_files": output_files,
        "output_files_sha256": output_files_sha256,
        "outcome_sha256": outcome_sha256,
        "evidence_index_sha256": evidence_index_sha256,
        "semantic_projection_file_sha256": semantic_projection_file_sha256,
        "semantic_projection_sha256": semantic_projection_sha256,
        "finalizer_closure": finalizer_closure,
        "finalizer_dependency_manifest_sha256": finalizer_dependency_manifest_sha256,
        "interpreter": finalizer_closure["interpreter"],
        "interpreter_sha256": finalizer_closure["interpreter_sha256"],
        "network": network,
        "additional_model_calls": 0,
        "additional_browser_actions": 0,
        "raw_source_mutated": False,
        "output_schema_valid": True,
    }


def build_local_finalizer_invocation(
    *,
    interpreter: str,
    dependency_site_packages: str,
    repository_source_root: str,
    finalizer_source: str,
    execution_contract: str,
    execution_contract_sha256: str,
    command_manifests: str,
    command_manifests_sha256: str,
    condition_plan: str,
    raw_root: str,
    raw_output_relative: str,
    finalized_root: str,
    finalized_output_relative: str,
    artifact_root: str,
    raw_attempt_manifest: str,
    raw_attempt_receipt: str,
    run_id: str,
    package_commit: str,
    finalizer_commit: str,
    finalizer_source_sha256: str,
    finalizer_projection_source_sha256: str,
    finalizer_dependency_manifest_sha256: str,
    frozen_run_manifest: str,
    frozen_run_manifest_sha256: str,
    replacement_image_id: str,
    host_cleanup_receipt: str,
    evaluator_root: str,
    evaluator_overlay_revalidation: str,
    dataset: str,
    score_schema: str,
    evidence_schema: str,
    runtime_qualification: str,
    runtime_qualification_sha256: str,
) -> dict[str, object]:
    """Project one explicit offline post-termination finalizer invocation."""

    return {
        "argv": [
            interpreter,
            finalizer_source,
            "--execution-contract",
            execution_contract,
            "--execution-contract-sha256",
            execution_contract_sha256,
            "--command-manifests",
            command_manifests,
            "--command-manifests-sha256",
            command_manifests_sha256,
            "--condition-plan",
            condition_plan,
            "--raw-attempt-root",
            raw_root,
            "--raw-output-relative",
            raw_output_relative,
            "--finalized-attempt-root",
            finalized_root,
            "--finalized-output-relative",
            finalized_output_relative,
            "--artifact-root",
            artifact_root,
            "--raw-attempt-manifest",
            raw_attempt_manifest,
            "--raw-attempt-receipt",
            raw_attempt_receipt,
            "--run-id",
            run_id,
            "--package-commit",
            package_commit,
            "--finalizer-commit",
            finalizer_commit,
            "--finalizer-execution-mode",
            "qualified-local",
            "--finalizer-source-sha256",
            finalizer_source_sha256,
            "--finalizer-projection-source-sha256",
            finalizer_projection_source_sha256,
            "--finalizer-dependency-manifest-sha256",
            finalizer_dependency_manifest_sha256,
            "--finalizer-runtime-qualification",
            runtime_qualification,
            "--finalizer-runtime-qualification-sha256",
            runtime_qualification_sha256,
            "--frozen-run-manifest",
            frozen_run_manifest,
            "--frozen-run-manifest-sha256",
            frozen_run_manifest_sha256,
            "--replacement-image-id",
            replacement_image_id,
            "--host-cleanup-receipt",
            host_cleanup_receipt,
            "--evaluator-root",
            evaluator_root,
            "--evaluator-overlay-revalidation",
            evaluator_overlay_revalidation,
            "--dataset",
            dataset,
            "--score-schema",
            score_schema,
            "--evidence-schema",
            evidence_schema,
        ],
        "environment": {
            "PYTHONPATH": f"{dependency_site_packages}:{repository_source_root}",
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONNOUSERSITE": "1",
            "CUDA_VISIBLE_DEVICES": "",
        },
        "network": "socket-construction-denied",
    }
