"""Evidence-preserving execution primitives for GIC Lab experiments."""

from .artifacts import (
    ArtifactError,
    ArtifactRecordWriter,
    ArtifactWorkspace,
    artifact_record,
    sha256_file,
    validate_artifact_directory,
)
from .budget import BudgetContractChanged, BudgetExceeded, BudgetGuard
from .events import EventStreamError, JsonlEventWriter, read_events, validate_event_stream
from .executor import DryRunReport, ExecutionOutcome, LocalRunExecutor, RunSession, render_command
from .models import (
    AdapterEventType,
    ArtifactPolicy,
    ArtifactRecord,
    BudgetUsage,
    CommandSpec,
    EventProvenance,
    EventType,
    ExecutionAuthorization,
    ExecutionBackend,
    ExecutionContract,
    HarnessEvent,
    IncrementalLimitEnforcement,
    InheritedEnvironmentBinding,
    InputTreeBinding,
    NonWallResource,
    NonWallResourceAccounting,
    NormalizedEvent,
    OwnedOutputRoot,
    ResourceProjection,
    RunBudget,
    RunIdentity,
    RunPlan,
    RunProfile,
    SourceVersions,
    WorkingDirectoryIdentity,
    WorkloadKind,
    command_document,
    command_sha256,
    inherited_environment_binding,
    input_tree_binding,
    input_tree_sha256,
)
from .plan import RunPlanError, load_run_plan, run_plan_document, validate_run_plan_data
from .policy import (
    ExecutionDisallowed,
    ProjectExecutionState,
    execution_blockers,
    load_project_execution_state,
)
from .safety import CredentialExposureError

__all__ = [
    "AdapterEventType",
    "ArtifactError",
    "ArtifactPolicy",
    "ArtifactRecord",
    "ArtifactRecordWriter",
    "ArtifactWorkspace",
    "BudgetContractChanged",
    "BudgetExceeded",
    "BudgetGuard",
    "BudgetUsage",
    "CommandSpec",
    "CredentialExposureError",
    "DryRunReport",
    "EventProvenance",
    "EventStreamError",
    "EventType",
    "ExecutionAuthorization",
    "ExecutionBackend",
    "ExecutionContract",
    "ExecutionDisallowed",
    "ExecutionOutcome",
    "HarnessEvent",
    "IncrementalLimitEnforcement",
    "InheritedEnvironmentBinding",
    "InputTreeBinding",
    "JsonlEventWriter",
    "LocalRunExecutor",
    "NonWallResource",
    "NonWallResourceAccounting",
    "NormalizedEvent",
    "OwnedOutputRoot",
    "ProjectExecutionState",
    "ResourceProjection",
    "RunBudget",
    "RunIdentity",
    "RunPlan",
    "RunPlanError",
    "RunProfile",
    "RunSession",
    "SourceVersions",
    "WorkingDirectoryIdentity",
    "WorkloadKind",
    "artifact_record",
    "command_document",
    "command_sha256",
    "execution_blockers",
    "inherited_environment_binding",
    "input_tree_binding",
    "input_tree_sha256",
    "load_project_execution_state",
    "load_run_plan",
    "read_events",
    "render_command",
    "run_plan_document",
    "sha256_file",
    "validate_artifact_directory",
    "validate_event_stream",
    "validate_run_plan_data",
]
